sonar.projectKey=chiche_chicheagil
sonar.organization=chiche

sonar.sources=.
sonar.exclusions=**/test.py,**/test.py
sonar.tests=.
sonar.test.inclusions=**/test.py,**/_test.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11